config/routes.rb
Prepify::Application.routes.draw do
  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users do
    resources :results
  end

  resources :lessons do
    resources :questions do
    end
  end
  
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  has_many :results

  
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  has_many :questions
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers
  belongs_to :lesson
  has_many :results


  def as_json(options={})
    {
      id: self.id,
      lesson_id: self.lesson_id,
      level: self.level,
      equation: self.equation,
      description: self.description,
      answers: self.answers.each do |answer|
        { id: answer.id,
          value: answer.value,
          correct: answer.correct,
          explanation: answer.explaination
        }
      end 
    }
  end
end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
  belongs_to :answer
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :results
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def index
    @answers = Answer.find_all_by_question_id(params[:question_id])

    respond_to do |format|

      format.html # index.html.erb
      format.json { render json: @answers }

    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController

  def index
    @lessons = Lesson.all
  end

  def show
    @lesson = Lesson.find(params[:id])
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.find_all_by_lesson_id(params[:lesson_id])
    
    @question = @questions.first
    
    respond_to do |format|

      format.html # index.html.erb
      format.json { render json: @questions }

    end

  end

  def show
    @question = Question.find_by_id(params[:id])

    respond_to do |format|

      format.html # show.html.erb
      format.json { render json: @question }

    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :update_sanitized_params, if: :devise_controller?

  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:email, :password, :password_confirmation)}
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:email, :password, :password_confirmation, :current_password)}
  end

end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def create
  end

  def show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lesson_helper.rb
module LessonHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/answers/index.html.erb
<h1>Answers#index</h1>
<p>Find me in app/views/answers/index.html.erb</p>
<%= params%>

<%= @answers.each { |answer| answer.value}%>

app/views/home/index.html.erb
<div class="splash-image">
	<div class="header-space"></div>
	
	<div class="logo-box">
		<div class="text">
			<h1><%=image_tag "logo-home.png", :class => "logo"%></h1>
			<p>FREE ONLINE SAT PREP</p>
		</div>
	</div>

	<div class="footer-box"></div>
	

  <div class="signup-form">
    <div class="row collapse">
      <div class="small-10 columns">
        <input type="text" placeholder="Sign up now to start practicing">
      </div>
      <div class="small-2 columns">
        <a href="lessons#index" class="button round postfix">Go!</a>
      </div>
    </div>
	</div>

</div>

<div class="splash-video">
	<br>
	<div class="large-5 columns small-12">
		<div class="title">
			<h1>ABOUT</h1>
			<hr>
		</div>	
		<p>Prepify is FREE, online, and computer-adaptive SAT prep for any
		student - anywhere.</p>
		<p>Our curriculum is designed by top instructors with experience teaching - and beating - the test.</p>
		<p>In addition to providing an open platform for SAT prep, Prepify matches admissions counselors with top-flight test takers based on factors like the student's profile, interest, and past performance.</p>
		<p>Prepify was founded by students at The University of Texas at Austin and MakerSquare, including alumni of Teach for America.</p>
	</div>
	<div class="large-7 small-12 columns right">
		<iframe width="640" height="360" src="//www.youtube.com/embed/P9OLgw9LBZo?rel=0" frameborder="0" allowfullscreen></iframe>
	</div>
</div>

<div class="profile-container">
	<div class="title">
		<h1>TOP PREPISTS</h1>
		<hr>
		<p>Check out these profiles of top-performing students on the Prepify platform.</p>
		<p>Want to make a difference?  Flip a Bitcoin to support these students'
		college funds!</p>
		<p>#PrepItForward</p>


	</div>
	
	<div class="profiles">
		<div class="large-4 columns">
			<div class="student-container"><%=image_tag "student1-square.jpg", :class => "student"%>
				<p class="name" style="margin-top:20px">THOMAS LEE</p>
				<p class="high-school">TURNER HIGH SCHOOL</p>
				<p class="city">WASHINGTON, DC</p>
				<br>
				<p class="quote">"I see myself attending Yale to study computer science."</p>
				<p><a href="#"><%= image_tag "bitcoin-button.png", :class => "bitcoin" %></a></p>
			</div>
		</div>

		<div class="large-4 columns">
			<div class="student-container"><%=image_tag "student2-square.jpg", :class => "student"%></div>
			<p class="name" style="margin-top:20px">LUCY GARCIA</p>
			<p class="high-school">SAN BENITO HIGH SCHOOL</p>
			<p class="city">HARLINGEN, TEXAS</p>
			<br>
			<p class="quote">"I've always wanted to go to Stanford."</p>
			<p><a href="#"><%= image_tag "bitcoin-button.png", :class => "bitcoin" %></a></p>
		</div>

		<div class="large-4 columns">
			<div class="student-container"><%=image_tag "student3-square.jpg", :class => "student"%></div>
			<p class="name" style="margin-top:20px">JESSICA WOODS</p>
			<p class="high-school">MADISON HIGH SCHOOL</p>
			<p class="city">BROOKLYN, NEW YORK</p>
			<br>
			<p class="quote">"I don't want to leave the city, so why not go to NYU?"</p>
			<p><a href="#"><%= image_tag "bitcoin-button.png", :class => "bitcoin" %></a></p>
		</div>

	</div>
</div>

<script type="text/javascript">
		// run script after document is ready
		$(function () {
	 
	   // install flowplayer to an element with CSS class "player"
	   $(".player").flowplayer();
	 
		});
</script>

app/views/layouts/_bottom_bar.html.erb
<div class="footer-bar">
	<div class="footer-logo">
		<%=link_to( image_tag("prepify-footer.png"), root_path) %></li>
	</div>
	<div class="footer-links">
		<ul class="links">
			<li>About</li>
			<li>Home</li>
			<li>Team</li>
			<li>Blog</li>
		</ul>
	</div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name == :notice ? "success" : "alert" %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
    	<%=link_to( image_tag("logo-home.png", :style => "height:100%"), root_path) %>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Login', new_user_session_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
<% else %>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Prepify" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Prepify" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>


    <!-- 1. skin for flowplayer -->
    <link rel="stylesheet" href="//releases.flowplayer.org/5.4.6/skin/minimalist.css">
 
    <!-- 2. flowplayer -->
    <script src="//releases.flowplayer.org/5.4.6/flowplayer.min.js"></script>


  </head>
  <body>
    <div class="main-container">
      <header>
        <%= render 'layouts/navigation' %>
      </header>
      <main role="main">
         <%= render 'layouts/messages' %>
         <%= yield %>
      </main>
      <div id="push"></div>
    </div>
    <div class="footer-container">
       <%= render 'layouts/bottom_bar' %>
    </div>
  </body>
</html>

app/views/lessons/index.html.erb
<% @lessons.each do |lesson | %>
	<div class="lesson">
		<h1 class="lesson-title"><%= link_to lesson.name, lesson_path(lesson) %></h1>
		<p class="lesson-text"><%= lesson.intro %></p>
	</div>
<% end %>

app/views/lessons/show.html.erb
<div class="lesson">
	<h1 class="lesson-title"><%= @lesson.name %></h1>

	<div class="large-6 columns">
		<div class="player">
	   <video preload="none">
	      <source type="video/mp4"  src="http://video-js.zencoder.com/oceans-clip.mp4">
	   </video>
		</div>
	</div>

	<script type="text/javascript">$(".player").flowplayer();</script>


	<div class="large-5 large-offset-1 columns">
		<p class="lesson-text"><%= @lesson.conclusion %></p>

		<a class="button" id="start_quiz" href="#" >Take Quiz</a>
	</div>
</div>

<div id='question'>

</div>
<!-- Backbone templaltes for ajaxy rendering -->
<div id="templates">
  <script class="question" type="text/template">
    <div class="row">
      <div class="columns small-12 medium-8 large-6 centered-small">
        <div class="question">
          <p>{{description}}</p>
          <p>{{equation}}</p>
        </div>
        <ol class="questions">
        <li id="answer_{{answers[0].id}}" class="answer_value"> {{answers[0].value}}
            <div class="opened"></div>
          </li>
          <li id="answer_{{answers[1].id}}" class="answer_value"> {{answers[1].value}}
            <div class="opened"></div>
          </li>
          <li id="answer_{{answers[2].id}}" class="answer_value"> {{answers[2].value}}
            <div class="opened"></div>
          </li>
          <li id="answer_{{answers[3].id}}" class="answer_value"> {{answers[3].value}}
            <div class="opened"></div>
          </li>

        </ol>
      </div>
    </div>
  </script>
  <script class="onGuessed" type="text/template">

      <h3 class="{{exclamation}}">{{exclamation}}!</h3>
      <p class="show_reason">Explain Why</p>
      <a class="button {{correctness}}">{{button_text}}</a>

  </script>

</div>

<script>
  var questionTemplateHtml = $('#templates .question').html();
  var questionTemplate = _.template(questionTemplateHtml);
  //
  var guessTemplateHtml = $('#templates .onGuessed').html();
  var guessTemplate = _.template(guessTemplateHtml);
  // insert first question
  $('#start_quiz').on('click', function () {
  	console.log("Click");
  	$('.lesson').remove();
  	this_lesson.fetch({success: function(){console.log('success'); insertQuestion(1,false)}});
  });
</script>

app/views/questions/index.html.erb
<div id='question'>

</div>
<!-- Backbone templaltes for ajaxy rendering -->
<div id="templates">
  <script class="question" type="text/template">
    <div class="row">
      <div class="columns small-12 medium-8 large-6 centered-small">
        <div class="question">
          <p>{{description}}</p>
          <p>{{equation}}</p>
        </div>
        <ol class="questions">
        <li id="answer_{{answers[0].id}}" class="answer_value"> {{answers[0].value}}
            <div class="opened"></div>
          </li>
          <li id="answer_{{answers[1].id}}" class="answer_value"> {{answers[1].value}}
            <div class="opened"></div>
          </li>
          <li id="answer_{{answers[2].id}}" class="answer_value"> {{answers[2].value}}
            <div class="opened"></div>
          </li>
          <li id="answer_{{answers[3].id}}" class="answer_value"> {{answers[3].value}}
            <div class="opened"></div>
          </li>

        </ol>
      </div>
    </div>
  </script>
  <script class="onGuessed" type="text/template">

      <h3 class="{{exclamation}}">{{exclamation}}!</h3>
      <p class="show_reason">Explain Why</p>
      <a class="button {{correctness}}">{{button_text}}</a>

  </script>

</div>

<script>
  var questionTemplateHtml = $('#templates .question').html();
  var questionTemplate = _.template(questionTemplateHtml);
  //
  var guessTemplateHtml = $('#templates .onGuessed').html();
  var guessTemplate = _.template(guessTemplateHtml);
  // insert first question
</script>

app/views/results/create.html.erb
<h1>Results#create</h1>
<p>Find me in app/views/activities/create.html.erb</p>

app/views/results/show.html.erb
<h1>Results#show</h1>
<p>Find me in app/views/activities/show.html.erb</p>

app/views/users/index.html.erb
<h3>Users</h3>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.email, user %> signed up <%= user.created_at.to_date %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<h3>User</h3>
<p>Email: <%= @user.email if @user.email %></p>